### PR TITLE
fix: select search on MultiSelect

### LINKED ISSUE #752: [Bug]: select search
### Tremor Version

3.9.1

### Link to minimal reproduction

https://stackblitz.com/edit/vitejs-vite-dyinnd?file=package.json,src%2Fmain.tsx

### Steps to reproduce

Issue 1:
- Open the search
- Search something
- Don't select any options, just blur the modal
- Open the search again
Watch that the options list has the value above, but the search does not have the value

 Issue 2:
- Open the search
- Search something
- Select one option
- Search somenthing again
Watch previously selected options disappear

### What is expected?

The search doesn't have any ux errors 

### What is actually happening?

Issue 1:
- Watch that the options list has the value above, but the search does not have the value

Issue 2:
-Watch previously selected options disappear

### What browsers are you seeing the problem on?

Chrome, Other

### Any additional comments?

https://github.com/tremorlabs/tremor/assets/60747616/dbcfe962-9816-4de2-bbdc-7ccaea0ed796

### PR DESCRIPTION
**Pull request by LauraCSDev**
**Description**

**Multiple Select**
- Add new value to keep availableOptions to search
- Reset the searchQuery when onBlur the list options
- Keep options selected when the user is searching

**Related issue(s)**
https://github.com/tremorlabs/tremor/issues/752

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New Feature (non-breaking change which adds functionality)
- [X] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [X] No

If yes, please describe the impact and migration path for existing applications:

**How has This been tested?**

**Screenshots (if appropriate):**

https://github.com/tremorlabs/tremor/assets/60747616/162a6861-1a00-45ab-ba56-3b2cc32ecba9

**The PR fulfills these requirements:**

- [ ] It's submitted to the `main` branch
- [X] When resolving a specific issue, it's referenced in the related issue section above
- [ ] My change requires a change to the documentation. (Managed by Tremor Team)
- [ ] I have added tests to cover my changes
- [ ] Check the ["Allow edits from maintainers" option](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork) while creating your PR.
- [X] Add refs #XXX or fixes #XXX to the related issue section if your PR refers to or fixes an issue.
- [X] By contributing to Tremor, you confirm that you have read and agreed to Tremor's [CONTRIBUTING.md](https://github.com/tremorlabs/tremor/blob/main/CONTRIBUTING.md) guideline. You also agree that your contributions will be licensed under the [Apache License 2.0](https://github.com/tremorlabs/tremor/blob/main/License) license.

### CODE REVIEW

**Comment by severinlandolt** [comment]
Hey @LauraCSDev! Thank you for this PR. There seems to be a little styling issue due to the span tag introduced in Line 294. The dividers have disappeared. May you have a look at this?

CleanShot 2023-10-13 at 13 36 03@2x

**Comment by LauraCSDev** [comment]
> Hey @LauraCSDev! Thank you for this PR. There seems to be a little styling issue due to the span tag introduced in Line 294. The dividers have disappeared. May you have a look at this?
> 
> CleanShot 2023-10-13 at 13 36 03@2x

It´s fixed now!

Thank you very much!

File: src/components/input-elements/MultiSelect/MultiSelect.tsx [hunk 1]
```diff
@@ -291,11 +291,12 @@ const MultiSelect = React.forwardRef<HTMLDivElement, MultiSelectProps>((props, r
                 value={searchQuery}
               />
             </div>
-            <span onBlur={handleResetSearch}>
-              <SelectedValueContext.Provider value={{ selectedValue: value }}>
-                {filteredOptions}
-              </SelectedValueContext.Provider>
-            </span>
+            <SelectedValueContext.Provider
+              {...{ onBlur: { handleResetSearch } }}
```
Comment (severinlandolt) [inline src/components/input-elements/MultiSelect/MultiSelect.tsx:295]: @mbauchet Do you think we can I improve this spread thing for the blur? Does it make sense to change the interface of the SelectedValueContext itself?
