### PR TITLE
fix: Password input blur and table styling

### LINKED ISSUE #864: [Bug]: Tab Key Does Not Navigate to Next Input on TextInput with Type "Password"
### Tremor Version

^3.11.0

### Link to minimal reproduction

-

### Steps to reproduce

    1. On the page, there is a TextInput element whose type prop is set to "password".
    2. Immediately following the password-type TextInput, there is another input element.
    3. After focusing on the first TextInput element (of type password), pressing the Tab key on the keyboard.

### What is expected?

When the Tab key is pressed, focus should move to the next input element. This facilitates easy keyboard navigation through the form.

### What is actually happening?

Pressing the Tab key does not shift the focus to the next input element when the TextInput is of type "password". This impedes keyboard navigation and negatively affects user experience.

### What browsers are you seeing the problem on?

Chrome, Firefox

### Any additional comments?

This issue seems to occur only when the TextInput's type is "password". For other input types (e.g., type="text"), this issue does not arise. Efficient keyboard navigation on forms is essential for user experience, making it crucial to address this issue. Additional testing might be beneficial to determine if this issue is specific to certain browsers or devices or if it is a more general problem.

### PR DESCRIPTION
**Pull request by severinlandolt**
**Description**

This PR fixes:
* The tabbing issue when TextInput is set to `password`
* Eye Icons in used to show/hide password

This PR removes:
* `tabular-nums` classes in the Table Component

**Related issue(s)**

* Closes #864

**What kind of change does this PR introduce?** (check at least one)

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New Feature (non-breaking change which adds functionality)
- [ ] New Feature (BREAKING CHANGE which adds functionality)
- [x] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**How has this been tested?**

**Screenshots (if appropriate):**

**The PR fulfils these requirements:**

- [x] It's submitted to the `main` branch
- [x] When resolving a specific issue, it's referenced in the related issue section above
- [x] My change requires a change to the documentation. (Managed by Tremor Team)
- [ ] I have added tests to cover my changes
- [x] Check the ["Allow edits from maintainers" option](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork) while creating your PR.
- [x] Add refs #XXX or fixes #XXX to the related issue section if your PR refers to or fixes an issue.
- [x] By contributing to Tremor, you confirm that you have read and agreed to Tremor's [CONTRIBUTING.md](https://github.com/tremorlabs/tremor/blob/main/CONTRIBUTING.md) guideline. You also agree that your contributions will be licensed under the [Apache License 2.0](https://github.com/tremorlabs/tremor/blob/main/License) license.

### CODE REVIEW

**Review by christopherkindl — APPROVED** [review]

File: src/components/input-elements/BaseInput.tsx [hunk 1]
```diff
@@ -49,21 +49,28 @@ const BaseInput = React.forwardRef<HTMLInputElement, BaseInputProps>((props, ref
...
+      node.focus();
     }
+
+    return () => {
+      if (node) {
+        node.removeEventListener("focus", handleFocus);
+        node.removeEventListener("blur", handleBlur);
+      }
+    };
+    // eslint-disable-next-line react-hooks/exhaustive-deps
```
Comment (severinlandolt) [inline src/components/input-elements/BaseInput.tsx]: @mbauchet Do you spot code smell or bad practice? Was a bit chaotic getting to a working solution (has to work with `autoFocus`, passwords and regular input
