### PR TITLE
fix: add onValueChange prop to TextInput

### LINKED ISSUE #628: [Feature]: TextInput should have onValueChange props
### What problem does this feature solve?

Controlled state for the TextInput component 

### What does the proposed API look like?

   <TextInput
                    icon={SearchIcon}
                    placeholder="Search by order ID or phone number"
                    enableClear
                    onValueChange={(value) => {
                      setSearch(value);
                    }}
                    value={search}
                  />

### PR DESCRIPTION
**Pull request by jzfrank**
**Description**

Add `onValueChange` prop to `TextInput`. 

This feature is more for consistency: since `NumberInput` supports `onValueChange`, it's natural to support this prop on `TextInput` as well. 

**Related issue(s)**
Closes https://github.com/tremorlabs/tremor/issues/628

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New Feature (non-breaking change which adds functionality)
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**How has This been tested?**

Storybook 
**Screenshots (if appropriate):**

image

**The PR fulfills these requirements:**

- [x] It's submitted to the `main` branch
- [x] When resolving a specific issue, it's referenced in the related issue section above
- [x] My change requires a change to the documentation. (Managed by Tremor Team)
- [ ] I have added tests to cover my changes
- [x] Check the ["Allow edits from maintainers" option](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork) while creating your PR.
- [x] Add refs #XXX or fixes #XXX to the related issue section if your PR refers to or fixes an issue.
- [x] By contributing to Tremor, you confirm that you have read and agreed to Tremor's [CONTRIBUTING.md](https://github.com/tremorlabs/tremor/blob/main/CONTRIBUTING.md) guideline. You also agree that your contributions will be licensed under the [Apache License 2.0](https://github.com/tremorlabs/tremor/blob/main/License) license.

### CODE REVIEW

File: src/components/input-elements/BaseInput.tsx [hunk 1]
```diff
@@ -13,6 +13,7 @@ export interface BaseInputProps extends React.InputHTMLAttributes<HTMLInputEleme
   errorMessage?: string;
   disabled?: boolean;
   stepper?: ReactNode;
+  onValueChange?: (value: string) => void;
```
Comment (severinlandolt) [inline src/components/input-elements/BaseInput.tsx:16]: Maybe include type `number` as well?

Comment (severinlandolt) [reply src/components/input-elements/BaseInput.tsx:16]: Ah, nevermind. Might lead to parsing issues

**Comment by severinlandolt** [comment]
@jzfrank Thank you for this PR, very helpful!
